[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyhctsa"
version = "0.0.1"
description = "My awesome package"
dependencies = [
    "numpy",
    "scipy"
]
