[build-system]
requires = ["setuptools>=68", "wheel", "numpy>=1.24"]
build-backend = "setuptools.build_meta"

[project]
name = "pyhctsa"
version = "0.1.1"
description = "Highly comparative time-series analysis in Python."
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10"
authors = [
  {name = "Joshua B. Moore", email = "joshua.moore@sydney.edu.au"}, 
  {name = "Ben D. Fulcher", email = "ben.fulcher@sydney.edu.au"}]
maintainers = [
  {name = "Joshua B. Moore", email = "joshua.moore@sydney.edu.au"},
  {name = "Ben D. Fulcher", email = "ben.fulcher@sydney.edu.au"}
]

dependencies = [
  "numpy",
  "scipy",
  "pyyaml",
  "statsmodels",
  "jpype1<1.7.0",
  "numba",
  "scikit-learn",
  "antropy",
  "ts2vg",
  "arch",
  "hmmlearn",
  "PyWavelets",
  "rich",
  "pathos"
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13"
]

[project.optional-dependencies]
test = ["pytest>=6.0", "pytest-cov", "pytest-mock"]

[project.urls]
Homepage = "https://dynamicsandneuralsystems.github.io/pyhctsa/"
Repository = "https://github.com/DynamicsAndNeuralSystems/pyhctsa"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
pyhctsa = [
  "configurations/*.yaml",
  "configurations/module_configs/*.yaml",
  "data/*.csv",
  "data/*.txt",
  "toolboxes/**/*",
]
