"""
A port of the nonlinear least-squares machinery behind MATLAB's
``fit(x, y, fittype(...))``.

This module ports that path for the unconstrained case, which is all the Curve
Fitting Toolbox uses when no ``Lower``/``Upper`` bounds are given. Without
finite bounds the reflective machinery collapses considerably: the scaling
matrix ``D`` is the identity, ``DG`` vanishes, no step is ever truncated at a
bound, and the reflected trial direction is never evaluated. What remains is
the two-dimensional subspace trust-region iteration.
"""

import numpy as np
from scipy.linalg import solve_triangular


_EPS = np.finfo(float).eps
_SQRT_EPS = np.sqrt(_EPS)


# ------------------------------------------------------------------------------
# Trust-region subproblem:
# min { g'*s + 0.5*s'*H*s : ||s|| <= delta }
# ------------------------------------------------------------------------------

def _seceqn(lam, eigval, alpha, delta):
    """
    The secular equation

        1 / delta - 1 / ||s(lambda)||

    evaluated at a scalar lambda.

    The trust-region problems generated by ``_trdog`` are at most two
    dimensional, so those cases are handled directly to avoid unnecessary
    temporary NumPy arrays.
    """
    n = eigval.size

    if n <= 2:
        w0 = eigval[0] + lam

        # Preserve the behaviour of the original:
        #
        # np.where(w != 0, alpha / w, np.inf)
        #
        # If w == 0, the squared contribution is inf and therefore
        # sqrt(1 / sum(...)) == 0.
        if w0 == 0:
            return 1.0 / delta

        q0 = alpha[0] / w0
        sm = q0 * q0

        if n == 2:
            w1 = eigval[1] + lam

            if w1 == 0:
                return 1.0 / delta

            q1 = alpha[1] / w1
            sm = sm + q1 * q1

        with np.errstate(divide="ignore", invalid="ignore"):
            value = np.sqrt(1.0 / sm)

        if np.isnan(value):
            value = 0.0

        return 1.0 / delta - value

    # General fallback.
    w = eigval + lam

    with np.errstate(divide="ignore", invalid="ignore"):
        m = np.where(
            w != 0,
            alpha / np.where(w != 0, w, 1),
            np.inf,
        )
        m = m * m
        value = np.sqrt(1.0 / np.sum(m))

    if np.isnan(value):
        value = 0.0

    return 1.0 / delta - value


def _secular_eqn_root(x, itbnd, eigval, alpha, delta, tol):
    """
    Zero of the secular equation to the RIGHT of the starting point ``x``.
    """
    itfun = 0
    dx = abs(x) / 2 if x != 0 else 0.5

    a = x
    c = a

    fa = _seceqn(a, eigval, alpha, delta)
    itfun += 1

    b = x + 1
    fb = _seceqn(b, eigval, alpha, delta)
    itfun += 1

    # Find change of sign.
    while (fa > 0) == (fb > 0):
        dx = 2 * dx

        if (fa > 0) != (fb > 0):
            break

        b = x + dx
        fb = _seceqn(b, eigval, alpha, delta)
        itfun += 1

        if itfun > itbnd:
            break

    fc = fb
    d = e = b - a

    # Main loop, exit from middle of the loop.
    while fb != 0:
        # Ensure that:
        #   b is the best result so far,
        #   a is the previous value of b,
        #   c is on the opposite side of the zero from b.
        if (fb > 0) == (fc > 0):
            c = a
            fc = fa
            d = b - a
            e = d

        if abs(fc) < abs(fb):
            a, b, c = b, c, b
            fa, fb, fc = fb, fc, fb

        if itfun > itbnd:
            break

        m = 0.5 * (c - b)
        toler = 2.0 * tol * max(abs(b), 1.0)

        if abs(m) <= toler or fb == 0.0:
            break

        # Choose bisection or interpolation.
        if abs(e) < toler or abs(fa) <= abs(fb):
            d = m
            e = m

        else:
            s = fb / fa

            if a == c:
                # Linear interpolation.
                p = 2.0 * m * s
                q = 1.0 - s

            else:
                # Inverse quadratic interpolation.
                q = fa / fc
                r = fb / fc
                p = s * (
                    2.0 * m * q * (q - r)
                    - (b - a) * (r - 1.0)
                )
                q = (
                    (q - 1.0)
                    * (r - 1.0)
                    * (s - 1.0)
                )

            if p > 0:
                q = -q
            else:
                p = -p

            if (
                2.0 * p < 3.0 * m * q - abs(toler * q)
                and p < abs(0.5 * e * q)
            ):
                e = d
                d = p / q

            else:
                d = m
                e = m

        a = b
        fa = fb

        if abs(d) > toler:
            b = b + d
        elif b > c:
            b = b - toler
        else:
            b = b + toler

        fb = _seceqn(
            b,
            eigval,
            alpha,
            delta,
        )
        itfun += 1

    return b, itfun


def _coeff_from_w(w, alpha):
    """
    The ``coeff = alpha ./ w`` step of ``trust``, preserving its handling of
    zeros in ``w``.

    The common 1-D and 2-D cases are handled directly to avoid temporary masks.
    """
    n = alpha.size

    if n <= 2:
        coeff = np.empty_like(alpha)

        for i in range(n):
            wi = w[i]
            ai = alpha[i]

            if wi != 0:
                c = ai / wi
            elif ai != 0:
                c = np.inf
            else:
                c = 0.0

            if np.isnan(c):
                c = 0.0

            coeff[i] = c

        return coeff

    coeff = np.zeros_like(alpha)

    nz = w != 0

    coeff[nz] = alpha[nz] / w[nz]
    coeff[~nz & (alpha != 0)] = np.inf
    coeff[np.isnan(coeff)] = 0.0

    return coeff


def _trust(g, H, delta):
    """
    Exact solution of the trust-region problem

        min { g's + 0.5 s'Hs : ||s|| <= delta }

    via the full eigen-decomposition and secular equation.
    """
    tol = 1e-12
    tol2 = 1e-8
    itbnd = 50

    key = 0
    lam_val = 0.0

    g = np.atleast_1d(
        np.asarray(g, dtype=float)
    )

    H = np.atleast_2d(
        np.asarray(H, dtype=float)
    )

    # ``_trdog`` produces trust-region subproblems of dimension at most 2.
    #
    # Avoid calling LAPACK for the trivial 1-D problem while retaining the
    # original eig/eigh distinction in the 2-D case.
    if H.shape == (1, 1):
        eigval = np.array(
            [H[0, 0]],
            dtype=float,
        )
        V = np.ones(
            (1, 1),
            dtype=float,
        )

    elif H.shape == (2, 2):
        # Equivalent to np.array_equal(H, H.T) for this matrix while avoiding
        # construction of H.T + a full array comparison.
        symmetric = (
            H[0, 0] == H[0, 0]
            and H[1, 1] == H[1, 1]
            and H[0, 1] == H[1, 0]
        )

        if symmetric:
            eigval, V = np.linalg.eigh(H)

        else:
            eigval, V = np.linalg.eig(H)
            eigval = np.real(eigval)
            V = np.real(V)

    elif np.array_equal(H, H.T):
        eigval, V = np.linalg.eigh(H)

    else:
        eigval, V = np.linalg.eig(H)
        eigval = np.real(eigval)
        V = np.real(V)

    jmin = int(np.argmin(eigval))
    mineig = eigval[jmin]

    alpha = -(V.T @ g)

    sig = (
        np.sign(alpha[jmin])
        + (alpha[jmin] == 0)
    )

    s = None
    laminit = 0.0

    if mineig > 0:
        # Positive-definite case.
        coeff = alpha / eigval
        lam_val = 0.0

        s = V @ coeff

        if np.linalg.norm(s) <= 1.2 * delta:
            key = 1
        else:
            laminit = 0.0

    else:
        # Indefinite case.
        laminit = -mineig

    if key == 0:
        if _seceqn(
            laminit,
            eigval,
            alpha,
            delta,
        ) > 0:

            b, _ = _secular_eqn_root(
                laminit,
                itbnd,
                eigval,
                alpha,
                delta,
                tol,
            )

            if abs(
                _seceqn(
                    b,
                    eigval,
                    alpha,
                    delta,
                )
            ) <= tol2:

                lam_val = b
                key = 2

                s = V @ _coeff_from_w(
                    eigval + lam_val,
                    alpha,
                )

                nrms = np.linalg.norm(s)

                if (
                    nrms > 1.2 * delta
                    or nrms < 0.8 * delta
                ):
                    key = 5
                    lam_val = -mineig

            else:
                lam_val = -mineig
                key = 3

        else:
            lam_val = -mineig
            key = 4

        if key > 2:
            arg = (
                np.abs(eigval + lam_val)
                < 10
                * _EPS
                * np.maximum(
                    np.abs(eigval),
                    1,
                )
            )

            alpha = np.where(
                arg,
                0.0,
                alpha,
            )

        s = V @ _coeff_from_w(
            eigval + lam_val,
            alpha,
        )

        nrms = np.linalg.norm(s)

        if key > 2 and nrms < 0.8 * delta:
            s = (
                s
                + np.sqrt(
                    delta**2 - nrms**2
                )
                * sig
                * V[:, jmin]
            )

        if key > 2 and nrms > 1.2 * delta:
            b, _ = _secular_eqn_root(
                laminit,
                itbnd,
                eigval,
                alpha,
                delta,
                tol,
            )

            lam_val = b

            s = V @ _coeff_from_w(
                eigval + lam_val,
                alpha,
            )

    val = (
        g @ s
        + 0.5 * (s @ (H @ s))
    )

    return s, val


# ------------------------------------------------------------------------------
# The 2-D subspace trial step (trdog.m, specialized to the unbounded case)
# ------------------------------------------------------------------------------


def _newton_direction(A, g):
    """
    The (Gauss-)Newton direction, i.e. the solution of

        (A'A)p = -g.

    ``pcgr`` preconditions with the exact QR factor of ``A`` produced by
    ``aprecon`` (``PrecondBandWidth = Inf``), so its single permitted CG
    iteration reproduces the direct solve.

    Only the direction survives -- ``trdog`` normalizes ``p`` immediately.
    """
    R = np.linalg.qr(
        A,
        mode="r",
    )

    r = -g

    try:
        tmp = solve_triangular(
            R,
            r,
            trans="T",
            lower=False,
            check_finite=False,
        )

        z = solve_triangular(
            R,
            tmp,
            lower=False,
            check_finite=False,
        )

    except (np.linalg.LinAlgError, ValueError):
        return r, 1

    if not np.all(np.isfinite(z)):
        return r, 1

    # Preserve the original floating-point association:
    #
    #     A.T @ (A @ z)
    #
    # Do not replace this with algebraically equivalent forms such as
    # (A.T @ A) @ z.
    Az = A @ z
    ww = A.T @ Az

    denom = z @ ww

    if denom <= 0:
        nz = np.linalg.norm(z)

        return (
            z if nz == 0 else z / nz
        ), 0

    return (
        (r @ z) / denom * z
    ), 1


def _trdog(g, A, delta, Z):
    """
    Reflected (2-D) trust-region trial step, with no finite bounds.
    """
    n = len(g)

    grad = g

    # D is identity, so the scaled gradient is just g.
    posdef = 1
    tol2 = _SQRT_EPS

    # Used in two different locations below.
    gnorm = (
        np.linalg.norm(grad)
        if n > 1
        else None
    )

    if Z is None:
        v1, posdef = _newton_direction(
            A,
            g,
        )

        nv1 = np.linalg.norm(v1)

        if nv1 > 0:
            v1 = v1 / nv1

        cols = [v1]

        if n > 1:
            # posdef < 1 would use D*sign(grad). D is identity and, with A'A
            # positive semi-definite, pcgr never reports negative curvature
            # anyway.
            v2 = (
                grad / gnorm
                if gnorm > 0
                else grad
            )

            v2 = (
                v2
                - v1 * (v1 @ v2)
            )

            nrmv2 = np.linalg.norm(v2)

            if nrmv2 > tol2:
                cols.append(
                    v2 / nrmv2
                )

        Z = np.column_stack(cols)

    # Reduce to the chosen subspace.
    #
    # D = I and DG = 0, so:
    #
    #     M = Z' (A'A) Z
    #
    # Preserve the original floating-point association exactly:
    #
    #     Z.T @ (A.T @ (A @ Z))
    #
    # Do NOT simplify to (A @ Z).T @ (A @ Z).
    AZ = A @ Z
    ATAZ = A.T @ AZ
    MM = Z.T @ ATAZ

    rhs = Z.T @ grad

    # Determine the 2-D trust-region solution.
    st, _ = _trust(
        rhs,
        MM,
        delta,
    )

    ss = Z @ st
    s = ss

    if np.any(np.isnan(s)):
        raise FloatingPointError(
            "NaN in the trust region step"
        )

    qpval1 = (
        rhs @ st
        + 0.5 * (st @ (MM @ st))
    )

    # The reflected direction is only evaluated when the step is truncated at
    # a bound, which cannot happen here, so qpval3 remains infinite.
    qpval2 = np.inf

    sg = None
    ssg = None

    if n > 1:
        # Evaluate along the gradient direction.
        ZZ = (
            grad
            / (
                gnorm
                + (gnorm == 0)
            )
        ).reshape(-1, 1)

        # Again preserve:
        #
        # ZZ.T @ (A.T @ (A @ ZZ))
        AZZ = A @ ZZ
        ATAZZ = A.T @ AZZ
        MMg = ZZ.T @ ATAZZ

        rhsg = ZZ.T @ grad

        stg, _ = _trust(
            rhsg,
            MMg,
            delta,
        )

        ssg = ZZ @ stg
        sg = ssg

        qpval2 = (
            rhsg @ stg
            + 0.5
            * (
                stg
                @ (
                    MMg
                    @ stg
                )
            )
        )

    # Choose the best of the two steps.
    if qpval2 <= qpval1:
        return (
            sg,
            ssg,
            qpval2,
            posdef,
            Z,
        )

    return (
        s,
        ss,
        qpval1,
        posdef,
        Z,
    )


# ------------------------------------------------------------------------------
# Finite-difference Jacobian
# ------------------------------------------------------------------------------


def _findiff_jac(
    resid_fn,
    x,
    fvec,
    diff_min_change,
    diff_max_change,
):
    """
    Forward finite-difference Jacobian.

    A single working copy of ``x`` is reused for all columns to avoid one array
    allocation per parameter.
    """
    n = len(x)

    J = np.empty(
        (len(fvec), n)
    )

    xp = x.copy()

    for j in range(n):
        xj = x[j]

        # MATLAB sign'(0) behaviour here is +1.
        sgn = (
            -1.0
            if xj < 0
            else 1.0
        )

        chg = (
            sgn
            * _SQRT_EPS
            * max(
                abs(xj),
                1.0,
            )
        )

        chg = (
            np.sign(chg)
            * min(
                max(
                    abs(chg),
                    diff_min_change,
                ),
                diff_max_change,
            )
        )

        xp[j] = xj + chg

        J[:, j] = (
            resid_fn(xp) - fvec
        ) / chg

        # Restore the original value before perturbing the next parameter.
        xp[j] = xj

    return J, n


# ------------------------------------------------------------------------------
# The main solver
# ------------------------------------------------------------------------------


def lsqcurvefit_trr(
    fun,
    x0,
    xdata,
    ydata,
    tol_fun=1e-6,
    tol_x=1e-6,
    max_iter=400,
    max_fun_evals=600,
    diff_min_change=1e-8,
    diff_max_change=0.1,
):
    """
    Minimize

        sum((fun(p, xdata) - ydata)**2)

    over ``p`` the way MATLAB's ``lsqcurvefit`` does with

        Algorithm = 'trust-region-reflective'

    and no bounds.

    Parameters
    ----------
    fun : callable
        ``fun(p, xdata)`` returning the model values.

    x0 : array-like
        Starting point for the coefficients (MATLAB's ``StartPoint``).

    xdata, ydata : array-like
        Data to fit.

    tol_fun : float
        Function tolerance.

    tol_x : float
        Parameter-step tolerance.

    max_iter : int
        Maximum number of trust-region iterations.

    max_fun_evals : int
        Maximum logical number of function evaluations.

    diff_min_change : float
        Minimum finite-difference perturbation.

    diff_max_change : float
        Maximum finite-difference perturbation.

    Returns
    -------
    numpy.ndarray
        Fitted coefficients.
    """
    xdata = np.asarray(
        xdata,
        dtype=float,
    )

    ydata = np.asarray(
        ydata,
        dtype=float,
    )

    x = (
        np.asarray(
            x0,
            dtype=float,
        )
        .ravel()
        .copy()
    )

    n = len(x)

    def resid(p):
        return (
            np.asarray(
                fun(
                    p,
                    xdata,
                ),
                dtype=float,
            ).ravel()
            - ydata
        )

    iter_count = 0
    num_fun_evals = 1

    delta = 10.0

    nrmsx = 1.0
    ratio = 0.0
    oval = np.inf

    Z = None
    posdef = 1

    fvec = resid(x)

    A, fdevals = _findiff_jac(
        resid,
        x,
        fvec,
        diff_min_change,
        diff_max_change,
    )

    num_fun_evals += fdevals

    if not np.all(np.isfinite(A)):
        raise FloatingPointError(
            "Jacobian undefined at the initial point"
        )

    g = A.T @ fvec
    val = fvec @ fvec

    if (
        not np.isfinite(val)
        or not np.all(np.isfinite(g))
    ):
        raise FloatingPointError(
            "Objective or its gradient undefined at the initial point"
        )

    ex = 0

    while not ex:
        # With no finite bounds, definev returns v = +/-1 and dv = 0,
        # therefore |v| = 1.
        optnrm = np.max(
            np.abs(g)
        )

        # --------------------------------------------------------------
        # Test for convergence
        # --------------------------------------------------------------

        diff = abs(
            oval - val
        )

        oval = val

        if (
            optnrm < tol_fun
            and posdef == 1
        ):
            ex = 1

        elif (
            nrmsx < 0.9 * delta
            and ratio > 0.25
            and diff
            < tol_fun
            * (
                1
                + abs(oval)
            )
        ):
            ex = 2

        elif (
            iter_count > 1
            and nrmsx < tol_x
        ):
            ex = 3

        elif (
            iter_count > max_iter
            or num_fun_evals > max_fun_evals
        ):
            ex = 4

        if ex:
            break

        # --------------------------------------------------------------
        # Determine trust-region correction
        # --------------------------------------------------------------

        sx, snod, qp, posdef, Z = _trdog(
            g,
            A,
            delta,
            Z,
        )

        nrmsx = np.linalg.norm(
            snod
        )

        newx = x + sx

        # --------------------------------------------------------------
        # Evaluate trial point
        # --------------------------------------------------------------

        newfvec = resid(
            newx
        )

        newval = (
            newfvec @ newfvec
        )

        # IMPORTANT:
        #
        # The original implementation evaluates:
        #
        #   1 residual +
        #   n residuals for a finite-difference Jacobian
        #
        # at every trial point, even when the point is rejected.
        #
        # We avoid physically calculating the rejected Jacobian but preserve
        # the same *logical* evaluation count. This retains the max_fun_evals
        # stopping behaviour of the original solver.
        num_fun_evals += (
            1 + n
        )

        finite_trial = np.all(
            np.isfinite(newfvec)
        )

        # --------------------------------------------------------------
        # Update trust-region radius
        # --------------------------------------------------------------

        if not finite_trial:
            delta = min(
                nrmsx / 20,
                delta / 20,
            )

        else:
            # ``aug`` involves dv, which is zero without finite bounds.
            ratio = (
                0.5
                * (
                    newval
                    - val
                )
            ) / qp

            if (
                ratio >= 0.75
                and nrmsx
                >= 0.9 * delta
            ):
                delta = (
                    2 * delta
                )

            elif ratio <= 0.25:
                delta = min(
                    nrmsx / 4,
                    delta / 4,
                )

        # --------------------------------------------------------------
        # Accept or reject trial point
        # --------------------------------------------------------------

        if newval < val:
            # The finite-difference Jacobian is required only for accepted
            # trial points. On rejected points it is discarded immediately
            # by the original algorithm.
            newA, _ = _findiff_jac(
                resid,
                newx,
                newfvec,
                diff_min_change,
                diff_max_change,
            )

            newgrad = (
                newA.T
                @ newfvec
            )

            x = newx
            val = newval
            g = newgrad
            A = newA

            # Recompute the subspace after accepting a new point.
            Z = None

            fvec = newfvec

        iter_count += 1

    return x


# ------------------------------------------------------------------------------
# Convenience fits
# ------------------------------------------------------------------------------


def fit_exp1(
    x,
    y,
    start_point=(1.0, -0.2),
):
    """
    Fit

        a * exp(b*x)

    as MATLAB's

        fit(x, y, fittype('a*exp(b*x)', 'options', s))

    does, where ``s`` sets ``Method`` to ``'NonlinearLeastSquares'`` and
    ``StartPoint`` to ``start_point``.

    Returns
    -------
    tuple of float
        Fitted ``(a, b)``.
    """
    p = lsqcurvefit_trr(
        lambda p, xd: (
            p[0]
            * np.exp(
                p[1] * xd
            )
        ),
        start_point,
        x,
        y,
    )

    return (
        float(p[0]),
        float(p[1]),
    )


def fit_poly1(
    x,
    y,
    start_point=(0.1, 0.0),
):
    """
    Fit

        a*x + b

    as MATLAB's

        fit(x, y, fittype('a*x+b', 'options', s))

    does with ``Method = 'NonlinearLeastSquares'`` and ``StartPoint`` set to
    ``start_point``.

    The model is linear in its coefficients, but the trust-region iteration can
    still stop short of the exact least-squares solution on the toolbox's
    default tolerances, so this does not generally agree with ``numpy.polyfit``.

    Returns
    -------
    tuple of float
        Fitted ``(a, b)``.
    """
    p = lsqcurvefit_trr(
        lambda p, xd: (
            p[0] * xd
            + p[1]
        ),
        start_point,
        x,
        y,
    )

    return (
        float(p[0]),
        float(p[1]),
    )


# ------------------------------------------------------------------------------
# Goodness of fit
# ------------------------------------------------------------------------------


def goodness_of_fit(
    y,
    y_fit,
    num_coeffs,
):
    """
    Goodness-of-fit statistics matching the ``gof`` struct returned by
    MATLAB's ``fit``.

    Note that ``rmse`` is the standard error

        sqrt(SSE / dfe)

    rather than the root-mean-square of the residuals.

    Parameters
    ----------
    y : array-like
        Observed values.

    y_fit : array-like
        Fitted values.

    num_coeffs : int
        Number of fitted coefficients, which determines the error degrees of
        freedom.

    Returns
    -------
    dict
        Keys are ``sse``, ``rsquare``, ``adjrsquare`` and ``rmse``.
    """
    y = np.asarray(
        y,
        dtype=float,
    )

    y_fit = np.asarray(
        y_fit,
        dtype=float,
    )

    n = len(y)
    dfe = n - num_coeffs

    residual = (
        y - y_fit
    )

    sse = np.sum(
        residual**2
    )

    centered = (
        y - np.mean(y)
    )

    sst = np.sum(
        centered**2
    )

    rsquare = (
        1 - sse / sst
    )

    return {
        "sse": sse,
        "rsquare": rsquare,
        "adjrsquare": (
            1
            - (
                1 - rsquare
            )
            * (n - 1)
            / dfe
        ),
        "rmse": np.sqrt(
            sse / dfe
        ),
    }


# ------------------------------------------------------------------------------
# Optional bitwise-regression helper
# ------------------------------------------------------------------------------


def assert_bitwise_equal(a, b):
    """
    Assert exact bitwise equality between two float64 arrays.

    Useful when regression-testing optimized solver implementations against the
    original implementation.
    """
    a = np.asarray(
        a,
        dtype=np.float64,
    )

    b = np.asarray(
        b,
        dtype=np.float64,
    )

    np.testing.assert_array_equal(
        a.view(np.uint64),
        b.view(np.uint64),
    )